import nextVitals from 'eslint-config-next/core-web-vitals';
import nextTs from 'eslint-config-next/typescript';
import prettier from 'eslint-config-prettier/flat';
import { defineConfig, globalIgnores } from 'eslint/config';

const eslintConfig = defineConfig([
    ...nextVitals,
    ...nextTs,
    prettier,
    {
        rules: {
            '@typescript-eslint/explicit-function-return-type': ['warn'],
            '@typescript-eslint/method-signature-style': ['error'],
            '@typescript-eslint/no-unused-vars': 'error',
            camelcase: ['warn'],
            indent: ['error', 4],
            'no-console': ['warn'],
            'no-duplicate-imports': ['error'],
            'no-empty': ['error'],
            'no-empty-character-class': ['error'],
            'no-empty-pattern': ['error'],
            'no-ex-assign': ['error'],
            'no-extra-boolean-cast': ['error'],
            'no-extra-semi': ['error'],
            'no-fallthrough': ['error'],
            'no-func-assign': ['error'],
            'no-global-assign': ['error'],
            'no-import-assign': ['error'],
            'no-inner-declarations': ['error'],
            'no-invalid-regexp': ['error'],
            'no-irregular-whitespace': ['error'],
            'no-loss-of-precision': ['error'],
            'no-misleading-character-class': ['error'],
            'no-mixed-spaces-and-tabs': ['error'],
            'no-new-symbol': ['error'],
            'no-nonoctal-decimal-escape': ['error'],
            'no-obj-calls': ['error'],
            'no-octal': ['error'],
            'no-prototype-builtins': ['error'],
            'no-redeclare': ['error'],
            'no-regex-spaces': ['error'],
            'no-self-assign': ['error'],
            'no-setter-return': ['error'],
            'no-shadow-restricted-names': ['error'],
            'no-sparse-arrays': ['error'],
            'no-this-before-super': ['error'],
            'no-unexpected-multiline': ['error'],
            'no-unreachable': ['error'],
            'no-unsafe-finally': ['error'],
            'no-unsafe-negation': ['error'],
            'no-unsafe-optional-chaining': ['error'],
            'no-unused-labels': ['error'],
            'no-useless-backreference': ['error'],
            'no-useless-catch': ['error'],
            'no-useless-escape': ['error'],
            'no-with': ['error'],
            quotes: ['error', 'single'],
            'require-await': ['warn'],
            'require-yield': ['error'],
            semi: ['error'],
            'use-isnan': ['error'],
            'valid-typeof': ['error'],
        },
    },
    globalIgnores([
        '.next/**',
        'out/**',
        'build/**',
        'next-env.d.ts',
        'public/service-worker.js',
    ]),
]);

export default eslintConfig;